<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        @page { margin: 10px; }
        body { font-family: 'Helvetica', sans-serif; margin: 0; padding: 0; background: #fff; }
        
        .container { 
            width: 100%; 
            margin-top: 10px;
        }

        .label-box {
            display: inline-block;
            vertical-align: top;
            /* Formula: Total Width / Columns - Gap for margins/borders */
            width: {{ (100 / $config['columns']) - 2 }}%; 
            margin: 0.5%;
            padding: 8px 2px;
            border: 0.1pt solid #dddddd;
            text-align: center;
            height: 160px; /* Adjust height as needed */
            overflow: hidden;
            box-sizing: border-box;
        }

        .store-title { font-size: 9px; font-weight: bold; margin-bottom: 5px; color: #333; }
        .product-title { font-size: 10px; height: 26px; line-height: 1.2; margin-bottom: 5px; overflow: hidden; }
        
        .code-wrapper { 
            width: 100%; 
            margin: 0 auto; 
            display: block;
        }

        /* Essential: Centers the barcode div generated by the library */
        .code-wrapper div { 
            margin: 0 auto !important; 
        }

        .sku-label { font-size: 8px; margin-top: 2px; }
        .price-tag { font-size: 12px; font-weight: bold; margin-top: 5px; display: block; }
    </style>
</head>
<body>
    <div class="container">
        @foreach($labels as $label)
            <div class="label-box">
                @if($config['show_store'])
                    <div class="store-title">{{ $config['store_name'] }}</div>
                @endif

                @if($config['show_product'])
                    <div class="product-title">{{ \Illuminate\Support\Str::limit($label['name'], 40) }}</div>
                @endif

                <div class="code-wrapper">
                    @if($config['type'] == 'barcode')
                        @php
                            // Dynamic scaling for barcodes to prevent overflow
                            $w = 1.1; 
                            if($config['columns'] == 3) $w = 0.9;
                            if($config['columns'] >= 4) $w = 0.7;
                        @endphp
                        {!! $dns1->getBarcodeHTML($label['sku'], 'C128', $w, 30) !!}
                    @else
                        @php
                            // Dynamic scaling for QR codes
                            $s = ($config['columns'] >= 4) ? 2 : 3;
                        @endphp
                        {!! $dns2->getBarcodeHTML($label['sku'], 'QRCODE', $s, $s) !!}
                    @endif
                    <div class="sku-label">{{ $label['sku'] }}</div>
                </div>

                @if($config['show_price'])
                    <div class="price-tag">${{ number_format($label['price'], 2) }}</div>
                @endif
            </div>
        @endforeach
    </div>
</body>
</html>